### ISSUE TITLE
Service requests are sent but never Received after the number of nodes reach around 98

### ISSUE THREAD

**Issue by Harold0** [ros2/rosidl_typesupport_opensplice#49]
Hello, I am new to ros2.
Service requests are sent (by client node) but never Received after the number of nodes reach around 98.
I searched this resp for whatever is related to 98,99,100,
and discovered a hard coded "99" here:

https://github.com/ros2/rosidl_typesupport_opensplice/blob/master/opensplice_cmake_module/config/ros_ospl.xml

Is this the problem?
If it is the problem, how do I modify and make it apply?

**Comment by clalancette** [comment]
Sorry, we don't support opensplice on any active ROS 2 release.  In point of fact, this repository should be archived, since we no longer support it.  If you are still having problems, please try again with a supported DDS implementation (Fast-RTPS or CycloneDDS), and open a report on the appropriate repository (https://github.com/ros2/rmw_fastrtps, https://github.com/ros2/rmw_cyclonedds, or https://github.com/ros2/ros2 if you think the problem is somewhere else).
